name: PR

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: jdx/mise-action@v2

      - run: bun install --frozen-lockfile
      - run: bun run build

  lint:
    if: github.event.pull_request.head.repo.fork == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: jdx/mise-action@v2

      - run: bun install --frozen-lockfile
      - run: bunx biome check

  autofix:
    if: github.event.pull_request.head.repo.fork == false
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}

      - uses: jdx/mise-action@v2

      - run: bun install --frozen-lockfile
      - run: bun run build
      - run: bunx biome check --write --unsafe

      - uses: EndBug/add-and-commit@v10
        with:
          default_author: github_actions
          message: "chore: apply formatting and generated files"
